### ISSUE TITLE
Exception when creating a bucket 

### ISSUE THREAD

**Issue by vadim-kor** [dresswithpockets/FakeS3#2]
Using .net6.
The bucket name is not empty, and the code previously worked with a real DB.

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at FakeS3.MemoryStore.CreateBucketAsync(String name)
   at FakeS3.Internal.FakeS3HttpMessageHandler.DoCreateBucketAsync(FakeS3Request fakeRequest)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationTok

**Comment by dresswithpockets** [comment]
Hey, I definitely could've been more clear about this in the readme, but the memory store is currently WIP. I recommend using the file store in the mean time.

I am currently working on a few improvements, including adding support for an in-memory store.

**Comment by dresswithpockets** [comment]
Think this was fixed with https://github.com/dresswithpockets/FakeS3/commit/8d23785dd73e46d054a78e68d298199c2e0de485

I've updated the nuget packages to 0.2.0 with many changes, including a complete in-memory implementation, as well as support for .net 6. @vadim-kor can you pull the latest version and attempt to replicate once more?
